### PR TITLE
I Have Made this game adequately Cheesy (prompted by my issue)

### PR DESCRIPTION
**Pull request by ghost**
Honestly this is quite possibly the best code ever conceived by humanity as a species.
I hope you cherish these alterations to your project!

(you need to manually enable cheese mode)

### CODE REVIEW

**Comment by HenryDewsnap** [comment]
gotta love cheese

**Comment by Explorer017** [comment]
i agree with the cheese statement

**Comment by HenryDewsnap** [comment]
good lad

**Comment by Explorer017** [comment]
🧀

**Comment by Explorer017** [comment]
- [ ] cheese
- [ ] cheese
- [ ] cheese

**Comment by HenryDewsnap** [comment]
hmm hard choice, I choose CHEESE!

**Comment by Explorer017** [comment]
cheese

**Comment by HenryDewsnap** [comment]
image

**Comment by HenryDewsnap** [comment]
well said Owner o' cheese repository

**Comment by Explorer017** [comment]
# cheese

**cheese** cheese cheese _cheese?_

## cheese?

- cheese
- cheese
- cheese

## cheese!

> cheese cheese cheese

^ cheese cheesington - top cheese professor

## cheese.

- [ ] cheese
- [ ] cheese

cheese!

**Pull request merged**
